# Generated by Django 5.0.1 on 2026-01-20 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency_symbol', models.CharField(max_length=5)),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, help_text='Default tax rate for this country', max_digits=5)),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('scooter', 'Electric Scooter')], default='car', max_length=50)),
                ('default_fuel_cost_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_maintenance_cost_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_depreciation_rate_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('depreciation_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_estimate', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('profit_per_hour', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('profit_per_km', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('profit_per_order', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
