# Generated by Django 5.0.1 on 2026-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_maintenance_cost_per_km',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='maintenance_cost',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_vehicle_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='worksession',
            name='vehicle_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
