# Generated by Django 5.0.1 on 2026-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_default_maintenance_cost_per_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_vehicle_rent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rent amount for the specified frequency', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
    ]
