# Generated by Django 5.0.1 on 2026-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_default_vehicle_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Pro subscription status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_current_period_end',
            field=models.DateTimeField(blank=True, help_text='Current billing period end date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True),
        ),
    ]
