# Generated by Django 5.0.1 on 2026-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_is_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courier_type',
            field=models.CharField(choices=[('SOLOPRENEUR', 'Solopreneur'), ('FLEET_COMPANY', 'Fleet / Company')], default='FLEET_COMPANY', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Application fee percentage for Fleet/Company', max_digits=5),
        ),
        migrations.AddField(
            model_name='worksession',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated application fee based on courier type', max_digits=10),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='platform_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fees charged by the delivery platform', max_digits=10),
        ),
    ]
