# Generated by Django 5.0.1 on 2026-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_courier_type_userprofile_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_end_time',
            field=models.TimeField(blank=True, help_text='Default end time for sessions', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_start_time',
            field=models.TimeField(blank=True, help_text='Default start time for sessions', null=True),
        ),
    ]
