# Generated by Django 5.0.1 on 2026-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_default_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='platforms',
            field=models.ManyToManyField(blank=True, help_text='Platforms enabled for this user', related_name='users', to='api.platform'),
        ),
    ]
