# Generated by Django 5.0.1 on 2026-02-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userprofile_stripe_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ls_card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_status',
            field=models.CharField(default='inactive', max_length=20),
        ),
    ]
