# Generated by Django 5.0.1 on 2026-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_ls_card_brand_userprofile_ls_card_last4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ls_billing_interval',
            field=models.CharField(default='monthly', help_text='monthly | yearly', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ls_plan_name',
            field=models.CharField(default='starter', help_text='starter | pro', max_length=50),
        ),
    ]
