# Generated by Django 5.0.1 on 2026-02-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_webhookevent_worksession_webhook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=300, help_text='Remaining session credits'),
        ),
    ]
